apiVersion: batch/v1
kind: CronJob
metadata:
  name: crj-ysql-ingestion
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crj-ysql-ingestion
            image: nobrejacubovski/ingestion-data-stores:0.2
            imagePullPolicy: IfNotPresent
            command: ["python3.9","cli.py","ysql"]
          restartPolicy: OnFailure
