apiVersion: batch/v1
kind: CronJob
metadata:
  name: crj-mysql-ingestion
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crj-mysql-ingestion
            image: nobrejacubovski/ingestion-data-stores:1.1
            imagePullPolicy: IfNotPresent
            command: ["python3.9","cli.py","mysql"]
          restartPolicy: OnFailure


