version: '2'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui2
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=ingestion-edh
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=34.134.204.228:9094
  
  kafka-connect-ui:
    image: landoop/kafka-connect-ui
    container_name: kafka-connect-ui
    ports:
      - "8000:8000"
    restart: always
    environment:
      - CONNECT_URL=34.123.94.43:8083

  schema-registry:
    image: landoop/schema-registry-ui
    container_name: schema-registry-ui
    ports:
      - "8001:8081"
    restart: always
    environment:
      - SCHEMAREGISTRY_URL=35.225.94.129:8081