version: '2'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui2
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=ingestion-edh
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=34.134.204.228:9094
  
  kafka-connect-ui:
    image: landoop/kafka-connect-ui
    container_name: kafka-connect-ui
    ports:
      - "8000:8000"
    restart: always
    environment:
      - CONNECT_URL=34.70.98.81:8083
